### PR TITLE
Implement bb protocol

### PR DESCRIPTION
**Pull request by werberson**
Implement full [bb-protocol](https://github.com/labbsr0x/bb-protocol)

- [x] Update docs on `README.md` file
- [x] Add feature to override `IsStatusError` function
- [x] Add dependency metrics

### CODE REVIEW

**Review by eabili0 — APPROVED** [review]

**Comment by eabili0** [comment]
@werberson, I noticed it does not implement an API for dependency metrics as defined by the protocol. Do you plan to include that in this PR or should we do it in another issue?

**Comment by eabili0** [comment]
```
dependency_request_seconds_bucket{name, type, status, isError, errorMessage, method, addr, le}
dependency_request_seconds_count{name, type, status, isError, errorMessage, method, add}
dependency_request_seconds_sum{name, type, status, isError, errorMessage, method, add}
```

**Comment by werberson** [comment]
Yes, I'll include in this PR.

**Review by eabili0 — APPROVED** [review]

**Comment by eabili0** [comment]
Very nice work @werberson, thank you so much!

**Pull request merged**
